### ISSUE TITLE
detail	"Authentication credentials were not provided."

### ISSUE THREAD

**Issue by Sispheor** [marcelo225/django-keycloak-auth#1]
Seems that "HTTP_AUTHORIZATION" is not present in the request.META.
Maybe I forgot a config on keycloak side?

**Comment by marcelo225** [comment]
Hi, @Sispheor 

Could you explain better your question? How are you doing in your case? 
If I understand your question, this library works in **passive mode**, in other words, firstly, you gotta authenticate on Keycloak with your credencials. After it all, you'll receive the access token that you can pass it into the **Authorization** header before you call your backend. 
This is the following code, using curl as would be it:
`curl -H 'Accept: application/json' -H "Authorization: Bearer ${YOUR_KEYCLOAK_AUTHENTICATED_TOKEN}" http://your_api.com`

Your authorization is already coming inside the JWT token where you configured Keycloak roles.

**Comment by Sispheor** [comment]
Hi, thanks for your answer.

First, I based the authentication on the lib [mozilla-django-oidc](https://mozilla-django-oidc.readthedocs.io/).

If I understand well, your lib only focus on permissions from the received token, right?

I did setup the lib like described in the doc.

I created a testing view
```python
class TestView(APIView):
   
    keycloak_roles = {
        'GET': ['test-role'],
    }

    def get(self, request, format=None):      
        # list of token roles
        print(request.roles)
        return super().get(self, request)
```

I fall[ in this retuned json](https://github.com/marcelo225/django-keycloak-auth/blob/master/django-keycloak-auth/middleware.py#L91) because META in my request doesn't contain HTTP_AUTHORIZATION.

Maybe I forgot a step after the login from keycloak.

**Comment by marcelo225** [comment]
@Sispheor 
Dead right, bro!

This lib only focuses on authorizations from the received token, in other words, this library supposes you must have a JWT authenticated token.

Before you call some endpoint, you must set in your HTTP header the attribute **Authorization**: **Bearer  YOUR_TOKEN** as I had described above.

In [this code line](https://github.com/marcelo225/django-keycloak-auth/blob/master/django-keycloak-auth/middleware.py#L90), Django Framework (behind of scenes) already knows it gets **Authorization** header value through request.META

See **request.META** documentation here: https://docs.djangoproject.com/en/dev/ref/request-response/#django.http.HttpRequest.META

Right?

I hope you got it!

**Comment by Sispheor** [comment]
Yep. That's the missing part!
Thanks for your time and this lib!

**Comment by marcelo225** [comment]
@Sispheor 
No worries, man!
Self free to ask me!

**Comment by andjimrio** [comment]
I am using now your library, and this issue was very useful for me!

**Comment by marcelo225** [comment]
@andjimrio thanks, man. 
I hope it helps you and other people too. 
If you want to contribute, feel free, bro!
