### ISSUE TITLE
Netbox django-keycloak-auth integration

### ISSUE THREAD

**Issue by beholdenkey** [marcelo225/django-keycloak-auth#10]
So I am attempting to use this application to allow Netbox to use the Keycloak API for Authentication. I was wondering if anyone has had any success in this area. I have also attempted to use a basic project app as well and have had little success. Any help is appreciated.

**Comment by marcelo225** [comment]
Hi, @beholdenkey 
Sorry about the delay, but could you explain better what you need?
I didn't get your thoughts.

**Comment by beholdenkey** [comment]
Hey, @marcelo225, it's all good. I ended up using the Django Auth package and ended up using a Fork of Netbox.
