### ISSUE TITLE
Pass userinfo into views

### ISSUE THREAD

**Issue by Madko** [marcelo225/django-keycloak-auth#11]
Hi,

I'd like my backend to get some userinfo from keycloak via the bearer token.

is there a way to pass userinfo to the view ?

I've added
```
request.userinfo = self.keycloak.userinfo(token)
```
at the end of the middleware.py and works perfectly. Is it ok or there is a better way ?

best regards

**Comment by marcelo225** [comment]
Hi, @Madko 
Sorry about my answer delay... so.... the main idea about this lib is simply to get the user roles directly.
What do you need specifically about user info in your API? All information on the bearer token?
best regards!

**Comment by Madko** [comment]
Yes getting the roles works perfectly and it's really great for managing permissions. I need to get the username in the backend so I can add it to data pushed by the client. I don't want to trust the username sent from the frontend.

**Comment by Foxeye73** [comment]
I actually agree with this need. I would like to track calls to my API, and if there was userinfo I would be able to add that to usage tracking

**Comment by marcelo225** [comment]
Hi @Madko and @Foxeye73 
I'm gonna code this functionality soon, right?
So... I need you to get patient with me, but I'm actually busy in the last days.

**Comment by Foxeye73** [comment]
I appreciate your time @marcelo225. I'm even keen to get involved if you need.

**Comment by marcelo225** [comment]
Hi, @Foxeye73 and @Madko 
I'm so sorry about my delay I had some personal problems to solve, though.
I've got a [PR](https://github.com/marcelo225/django-keycloak-auth/pull/16) about this issue.
Please, check it out before merging and pushing a new version with this functionallity.

Best regards!!

**Comment by marcelo225** [comment]
(PR)[https://github.com/marcelo225/django-keycloak-auth/pull/16] was merged successfully!
Enjoy it!

**Comment by Foxeye73** [comment]
Wonderful! Thank you
