### ISSUE TITLE
Feature Request: Decorator to control specific permissions on view functions

### ISSUE THREAD

**Issue by Foxeye73** [marcelo225/django-keycloak-auth#20]
So your config currently works great for REST style API, where you control the permissions on the request method.
One of the API classes I work with exposes the functions as endpoints, so there can be many functions that act as endpoint, and they can all be POST. I created a decorator to control permissions in this circumstance, which works well for me. Was wondering if you see value in adding something like this to your code base.

decorator:

```
def valid_roles(access_roles):
    def decorator(func):
        @wraps(func)
        def wrapped_func(self, request, *args, **kwargs):
            if len(set(request.roles) & set(access_roles)) == 0:
                raise exceptions.PermissionDenied(exceptions.PermissionDenied.default_detail)
            return func(self, request, *args, **kwargs)
        return wrapped_func
    return decorator
```

Example use:

```
class ExternalDemandActionAPI(ActionAPIView):
    permission_classes = []
    authentication_classes = []

    keycloak_roles = {
        'GET': ['api:get'],
        'POST': ['api:add', 'api:get', 'api:mod'],
        'UPDATE': ['api:mod', ],
        'DELETE': ['api:del', ],
        'PATCH': ['api:mod'],
    }

    @valid_roles(['api:demand:add'])
    def add_demand(self, request, params, *args, **kwargs):

        logger.debug(f'{params}')
        return params
```

**Comment by marcelo225** [comment]
Hi, @Foxeye73. Sorry about delay.

Nice ideia, bro. Could you propose some PR about this modification?
Thanks for getting a touch!
