### ISSUE TITLE
requirements-development.txt not provided

### ISSUE THREAD

**Issue by BassetSad** [marcelo225/django-keycloak-auth#22]
i couldn't find this file requirements-development.txt in the project so i couldn't install the dependencies

**Comment by marcelo225** [comment]
This file was a simple name example to put into your own desired dependencies. You don't even need to follow how i did it. I mean i wanted to separate 2 environments, if it was necessary. Right?

**Comment by marcelo225** [comment]
Hi, @BassetSad.
So as not to get confused, I've fixed [README.md](https://github.com/marcelo225/django-keycloak-auth/blob/master/README.md#install-this-package-to-pypi)
