### ISSUE TITLE
Logging doesn't work for keyclock requests

### ISSUE THREAD

**Issue by TimurSungatullin** [marcelo225/django-keycloak-auth#24]
I found the problem is that you are trying to get an error from method raise_for_status. But this method does not return an error, but raised does. 

I created a PR that solves this problem. https://github.com/marcelo225/django-keycloak-auth/pull/23

**Comment by marcelo225** [comment]
@TimurSungatullin the [0.9.6 release](https://pypi.org/project/django-keycloak-auth/0.9.6) has been created successfully.
Thanks!
