### ISSUE TITLE
Function based views

### ISSUE THREAD

**Issue by Leelith** [marcelo225/django-keycloak-auth#25]
Hello, is there a way to use this lib with function based views?

**Comment by marcelo225** [comment]
Hi @Leelith. Have you been able to check README out about this lib?
https://github.com/marcelo225/django-keycloak-auth#how-to-use

**Comment by Leelith** [comment]
> Hi @Leelith. Have you been able to check README out about this lib? https://github.com/marcelo225/django-keycloak-auth#how-to-use

Hello, yes! As far as I understand, this describes the use with class-based views. I want to apply this to a function with @api_view decorator for example. I've already wrote additional code for this, which adds @keycloak_roles decorator, but maybe I just didn’t understand how to work with the existing functionality.

My addition works like this

```
@keycloak_roles({'GET': ['some_role',...]})
@api_view
def some_api_function(request):
    ...
```

**Comment by SamuelBen-22** [comment]
@Leelith did you find any solution to use this lib with function based views? The docs doesn't have any solution for this.

**Comment by Leelith** [comment]
> @Leelith did you find any solution to use this lib with function based views? The docs doesn't have any solution for this.

Hello @SamuelBen-22, for now I'm using the decorator I wrote
https://github.com/Leelith/django-keycloak-auth/tree/decorator

Usage:
```
from django_keycloak_auth import keycloak_roles
...
@keycloak_roles({'GET': ['judge'], ...})
@api_view(('GET', ...))
def my_api_function(request):
    ...
```

**Comment by marcelo225** [comment]
@Leelith , could you create a PR about this? I'll merge it if you propose this PR, right?
Could you add some documentation in README on how to use this new functionality?
Thanks!

**Comment by marcelo225** [comment]
@Leelith PR was merged into master.
The new version is 0.97 now
Thanks for helping all of us!

**Comment by marcelo225** [comment]
@Leelith PR was merged into master.
The new version is 0.97 now
Thanks for helping all of us!
