### ISSUE TITLE
Assigning keycloak_roles to ModelViewSet prevents unauthenticated requests

### ISSUE THREAD

**Issue by singlerider** [marcelo225/django-keycloak-auth#27]
My Django Rest Framework application is still integrating auth. I wanted to test this library a bit before diving deep.

There is a docstring in the example `APIView` from the documentation that suggests that "Other HTTP methods will be allowed."

However, once that `keycloak_roles` attribute is assigned (at least in a `ModelViewSet`), it prevents other methods from being accessed.

---
Example `APIView`:

```python
class JudgementView(views.APIView):
    """
    Judgement endpoint
    This endpoint has configured keycloak roles only GET method.
    Other HTTP methods will be allowed.
    """
    keycloak_roles = {
        'GET': ['judge'],
    }
```

---

The following are from my project:

`settings.py`:

```python
# Exempt URIS
KEYCLOAK_EXEMPT_URIS = [
    '/schema/swagger', '/schema/redoc', '/schema/spectacular'
]
KEYCLOAK_CONFIG = {
    'KEYCLOAK_SERVER_URL': 'http://localhost:8080/auth',
    'KEYCLOAK_REALM': 'master',
    'KEYCLOAK_CLIENT_ID': 'client-backend',
    'KEYCLOAK_CLIENT_SECRET_KEY': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
}
```

`views.py`:

```python
class ApplicationViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows applications to be viewed or edited.
    """
    queryset = Application.objects.all()
    permission_classes = [permissions.AllowAny]
    serializer_class = ApplicationSerializer
    keycloak_roles = {
        # 'GET': ['director', 'judge', 'employee'],
        'POST': ['director', 'judge', ],
        # 'UPDATE': ['director', 'judge', ],
        # 'DELETE': ['director', 'judge', ],
        # 'PATCH': ['director', 'judge', 'employee'],
    }
```

I make no effort to properly authenticate, yet, but I would expect this `/applications` route to be able to see the `list` view (`GET`). Here is the result of attempting to perform a request with any method on the `/applications` route.

```json
{"detail": "Authentication credentials were not provided."}
```

---

Am I misunderstanding how to properly exempt specific methods? My application would support unauthenticated requests for some shared routes with specific methods (such as being able to submit an "`Application`" without having an account with `POST`).

**Comment by singlerider** [comment]
Is the preferred workaround using these `APIView`s or function-based views?

**Comment by singlerider** [comment]
This appears to be the offending line which catches any non-authenticated requests:

https://github.com/marcelo225/django-keycloak-auth/blob/master/django_keycloak_auth/middleware.py#L101

Perhaps this could instead only occur if an intended HTTP method is being invoked?

**Comment by singlerider** [comment]
Perhaps the following logic could be altered to include another check:

```python
        # Checks the URIs (paths) that doesn't needs authentication        
        if hasattr(settings, 'KEYCLOAK_EXEMPT_URIS'):
            path = request.path_info.lstrip('/')
            if any(re.match(m, path) for m in settings.KEYCLOAK_EXEMPT_URIS):
                if method not in keycloak_roles:  # pseudocode
                    return None
```

With this, I could exempt a URI, but override that exemption with an explicit mention of a `keycloak_roles` attribute.

**Comment by singlerider** [comment]
I'm increasing the scope of this issue and declaring that the tests are likely not actually testing intended behaviors:

I can `c`ontinue through any instance of this breakpoint and see that every instance of the `BankViewSet` is *always* identical:

`middleware.py` (note the breakpoint):

```python
    def process_view(self, request, view_func, view_args, view_kwargs):
        
        # for now there is no role assigned yet and no userinfo defined
        request.roles = []
        request.userinfo = []

        # Checks the URIs (paths) that doesn't needs authentication        
        if hasattr(settings, 'KEYCLOAK_EXEMPT_URIS'):
            path = request.path_info.lstrip('/')
            if any(re.match(m, path) for m in settings.KEYCLOAK_EXEMPT_URIS):
                import pdb; pdb.set_trace()
                # Checks to see if a request.method explicitly overwrites exemptions in SETTINGS
                if hasattr(view_func.cls, "keycloak_roles") and request.method not in view_func.cls.keycloak_roles:
                    return None
```

```
-> if hasattr(view_func.cls, "keycloak_roles") and request.method not in view_func.cls.keycloak_roles:
(Pdb) p view_func.cls.keycloak_roles
{'GET': ['director', 'judge', 'employee'], 'POST': ['director', 'judge'], 'UPDATE': ['director', 'judge'], 'DELETE': ['director', 'judge'], 'PATCH': ['director', 'judge', 'employee']}
(Pdb) c
> /home/user/git/django-keycloak-auth/django_keycloak_auth/middleware.py(89)process_view()
-> if hasattr(view_func.cls, "keycloak_roles") and request.method not in view_func.cls.keycloak_roles:
(Pdb) p view_func.cls.keycloak_roles
{'GET': ['director', 'judge', 'employee'], 'POST': ['director', 'judge'], 'UPDATE': ['director', 'judge'], 'DELETE': ['director', 'judge'], 'PATCH': ['director', 'judge', 'employee']}
(Pdb) c
> /home/user/git/django-keycloak-auth/django_keycloak_auth/middleware.py(89)process_view()
-> if hasattr(view_func.cls, "keycloak_roles") and request.method not in view_func.cls.keycloak_roles:
(Pdb) p view_func.cls.keycloak_roles
{'GET': ['director', 'judge', 'employee'], 'POST': ['director', 'judge'], 'UPDATE': ['director', 'judge'], 'DELETE': ['director', 'judge'], 'PATCH': ['director', 'judge', 'employee']}
(Pdb) c
```

I do not see a way to appropriately limit these test cases to limited `keycloak_roles`. I do not see where the assignment happens. I am opening a Pull Request to address both of these issues.

**Comment by marcelo225** [comment]
@singlerider, 

> However, once that keycloak_roles attribute is assigned (at least in a ModelViewSet), it prevents other methods from being accessed.
```
class JudgementView(views.APIView):
    """
    Judgement endpoint
    This endpoint has configured keycloak roles only GET method.
    Other HTTP methods will be allowed.
    """
    keycloak_roles = {
        'GET': ['judge'],
    }
```

I was wrong in writing out "Other HTTP methods will be allowed". Indeed the idea, by default, wasn't to permit not accessing other methods until it specifies the endpoint URL in `KEYCLOAK_EXEMPT_URIS` env variable as an exempt URL.

So... I thought interesting idea for your PR implementation. It never hit in my mind.

> Is the preferred workaround using these APIViews or function-based views?

You can use any Views you desire!
