### ISSUE TITLE
/admin AttributeError

### ISSUE THREAD

**Issue by chmoder** [marcelo225/django-keycloak-auth#29]
Adding `"django_keycloak_auth.middleware.KeycloakMiddleware",` to the settings `MIDDLEWARE` array causes the below error when accessing /admin:
```
Traceback (most recent call last):
  File "/Users/thomasfex/development/github/ItkBackend/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/thomasfex/development/github/ItkBackend/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 171, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/Users/thomasfex/development/github/ItkBackend/env/lib/python3.8/site-packages/django_keycloak_auth/middleware.py", line 91, in process_view
    is_api_view = True if str(view_func.cls.__qualname__) == "WrappedAPIView" else False
AttributeError: 'function' object has no attribute 'cls'
[03-11-23 13:38:09] django.server 500 "GET /admin/ HTTP/1.1" 500 95736
```

I think we can fix it on line [90 of middleware.py](https://github.com/marcelo225/django-keycloak-auth/blob/976708daf6973be919b0f28e6480b2cab8374fbe/django_keycloak_auth/middleware.py#L90) like so:
```python
try:      
    is_api_view = True if str(view_func.cls.__qualname__) == "WrappedAPIView" else False
except AttributeError as e:
    is_api_view = False
```

Is this a logical fix?  I can open a pr if that looks right.

**Comment by singlerider** [comment]
I'll add to my open PR to fix this. It's something I just ran into, myself.

**Comment by singlerider** [comment]
@chmoder I have tried out your suggestion and it seems to have worked. Here is the commit:

https://github.com/marcelo225/django-keycloak-auth/pull/28/commits/3c43a0a210d0d0522e918f0070ea1381947bc584

I can `drop` it if you would prefer to have your own PR up.

**Comment by chmoder** [comment]
Great!  This looks good to me and don't mind that this is added to your open PR.

**Comment by chmoder** [comment]
Closing as @singlerider is [adding this fix to their pr](https://github.com/marcelo225/django-keycloak-auth/pull/28/files#diff-e016ec9ece8af94d0b08127732bcd45f36b9b7301c5268ca7235cc34ba21c481R93).

**Comment by singlerider** [comment]
In the meantime, I have this project added to my `requirements.txt` as:

```
...
-e git+https://github.com/singlerider/django-keycloak-auth@3c43a0a210d0d0522e918f0070ea1381947bc584#egg=django_keycloak_auth
...
```
