### ISSUE TITLE
Realm roles support

### ISSUE THREAD

**Issue by olhybrius** [marcelo225/django-keycloak-auth#3]
Hi,

First of all, thanks for this library !

It could be useful to support realm roles as well instead of just client roles.

It shoudn't be too difficult to implement, my guess is slightly modifying keycloak.py like below would do the trick (lines 131 - 134) :

 ```
if not (self.client_id in token_decoded['resource_access'] or self.client_id in token_decoded['realm_access']) : 
        return None
resource_access = token_decoded['resource_access'].get(self.client_id, None)   
realm_access = token_decoded['realm_access']      
return resource_access.get('roles', None) or realm_access.get('roles', None)
```

I can make a PR for this if you want.

**Comment by marcelo225** [comment]
Hi @olhybrius 
You're wellcome to suggest updates about this lib. Feel free, bro!
Please, you can create a PR before i approve it.
Don't forget to create unit tests about new functionalities. Right?
Thanks a bunch!

**Comment by olhybrius** [comment]
@marcelo225 
Okay, I'm on it, I'll submit the PR when I'm done.

**Comment by marcelo225** [comment]
@olhybrius 
There we go!
The new version has been available!
I really appreciated you contributing to it.
