### ISSUE TITLE
Issue with Exempting Admin Path in New Module Versions

### ISSUE THREAD

**Issue by vardgeskarapetyan2** [marcelo225/django-keycloak-auth#31]
Hi everyone,

I hope this message finds you well. I've come across an issue while working with the latest versions of the module, specifically when attempting to exempt the admin path, as I used to do in older versions.

Here's a snippet of my code:
KEYCLOAK_EXEMPT_URIS = ["admin/"]

However, upon implementing this, I encountered the following error:
AttributeError: 'function' object has no attribute 'cls'
if hasattr(view_func.cls, "keycloak_roles") and request.method not in view_func.cls.keycloak_roles:
"GET /admin/ HTTP/1.1" 500 145

Interestingly, removing the "admin/" part from KEYCLOAK_EXEMPT_URIS resolved the issue for me. I would appreciate some guidance or clarification on whether this behavior is considered an issue in the current module versions.

Thank you for your time and assistance.

**Comment by singlerider** [comment]
My project does not exempt the `admin/` views and I still have full access to the Admin interface:

settings.py:
```python
KEYCLOAK_EXEMPT_URIS = [
    'schema/swagger', 'schema/redoc', 'schema/spectacular',
    'applications/', 'uploaded_files'
]
```

urls.py:
```python
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(router.urls)),
    path('auth/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('auth/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/spectacular', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger<format>/', swagger_schema_view.without_ui(cache_timeout=0), name='swagger_schema_json'),
    path('schema/swagger/', swagger_schema_view.with_ui('swagger', cache_timeout=0), name='swagger_schema_swagger_ui'),
    path('schema/redoc/', swagger_schema_view.with_ui('redoc', cache_timeout=0), name='swagger_schema_redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

@vardgeskarapetyan2 , you don't have access to Admin? I think the problem is the `Admin` stuff in Django doesn't implement "views" the same way as Django and Django Rest Framework, so the `cls` attribute would not exist in/on an Admin "view."

**Comment by singlerider** [comment]
For more clarification, my recent PR fixed it: https://github.com/marcelo225/django-keycloak-auth/issues/29. Using version `0.9.8` will resolve your error.

**Comment by marcelo225** [comment]
@vardgeskarapetyan2, as @singlerider has said, the `KEYCLOAK_EXEMPT_URIS` doesn´t work for Django views cause Django doesn't implement "views". For now, it just works for Django Rest Framework Views.

So let me know... why do you want to put 'admin' within `KEYCLOAK_EXEMPT_URIS` being the admin/ endpoint is already authenticated with user and password?

But I can write down some comments about Django views over the KEYCLOAK_EXEMPT_URIS variable in README.md, like

```python
# Exempt URIS
# For example: ['core/banks', 'swagger']
# This variable only works with Django Rest Framework Views, but not for native Django views.
KEYCLOAK_EXEMPT_URIS = []
```

Any thoughts?

**Comment by vardgeskarapetyan2** [comment]
@marcelo225  , @singlerider Thanks for your help! I ran into issues in older versions without specifying the admin path in keycloak_exempt, but it seems to be fixed in new versions. I think  updating  the readme  it's a good idea to keep things clear. Thanks!
