### ISSUE TITLE
Url Auth Error? 

### ISSUE THREAD

**Issue by williank** [marcelo225/django-keycloak-auth#36]
In the documentation you cite the Auth URL for "http://localhost:8080/auth" but I see that this URL no longer exists in the latest version of keycloak. It is currently "http://localhost:8080".

/auth is deprecated.!?!?!?!

**Comment by marcelo225** [comment]
@williank and @chmoder 
I just merged your PR into the master branch
The version is 1.0.0 now
Thanks for contributing!
