### ISSUE TITLE
Add Keycloak user UUID to request object

### ISSUE THREAD

**Issue by olhybrius** [marcelo225/django-keycloak-auth#5]
Hi,

I know it is slightly out of the scope of this library, but since the information is already there, I think it could be useful to include the Keycloak user UUID in the request object along with the roles. The information is available in the 'sub' attribute of the decoded token.

I can make a PR if you're interested.

**Comment by marcelo225** [comment]
@olhybrius 

I see, man. 
So... what is this useful for?
Could you give some examples for this new funcionality?
Thanks!

**Comment by olhybrius** [comment]
Well, in my own case, I have to manage, not only the access, but also the ownership of the resource so I can filter the queryset of the viewset based on the Keycloak user UUID found in the token. In other word, only the owner of the resource can see it.

Again, I know this is slightly out of the scope of this library, but the information is already there, so might as well include it.

**Comment by marcelo225** [comment]
@olhybrius sorry about my delay!
I'm in a rush with other things. I can't keep attention to these issues.
That's could be interesting and simple.
If you wanna implement this PR, feel free.
As I've said, I wanna keep this lib the most simply possible.
Thanks for contributing!
