### ISSUE TITLE
Authorization based on oAuth2 scopes

### ISSUE THREAD

**Issue by svituz** [marcelo225/django-keycloak-auth#9]
Is there the possibility to perform the authorization based on oauth2 scopes instead of keycloak roles? 
Would you consider implementing this possibility or merging a PR that implements the feature?

**Comment by marcelo225** [comment]
Hi, @svituz 

For now, I can't implement this feature. Who knows? When I have a longer time, hahaha. I'm in the rush in the last days.

If you have interesting to implement it, you can make it, but with this feature, you keep the most simple possible and keep what already exists.
I also need to change the API documentation to explain this new feature as I've made in the README, right?

Thanks for helping me!
